[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --title=scratchpad"
class = "scratchpad"
size = "100% 40%"

[scratchpads.discord]
animation = "fromRight"
command = "discord"
class = "discord"
size = "30% 90%"
lazy = true # Keeps Discord asleep/idle until you draw it out
